---
title: "introPage"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
```

# Project Overview

This report gives an overview of several facets of America's education system.
America's education system is unique, often confusing, and enormous. Thus, making
decisions when it comes to America's schools is very difficult. Our visualizations
depict the state of the system over the past could decades. We believe that it is
imperative to have the best possible education system to ensure the future of our
country.

## Audience

The report is straightforward enough to be understood and appreciated with anyone
with an interest in the American education system. However, the true intended
audience of the report are those making descisions about our education systems,
especially at higher levels, where even the smallest change can majorly impact
many children.

## Data

Our data is sourced from two places. Firstly, we used [Roy Garrard's data set](https://www.kaggle.com/noriuk/us-education-datasets-unification-project)
for data that goes into the 1990s to really give some of our visualizations a
historical perspective. While Garrard's data was very helpful, we took a deeper
dive into some more complex modern data by sourcing much of our data from 
[The Urban Institute's public API](https://educationdata.urban.org/documentation/schools.html#overview).
Initially, we planned on sourcing this data directly from the API, but all of
our calls were returning far too much data (multiple millions of rows), 
resulting in long loading times. Thus, we decided to simply download the data we
needed, and consolidate that data into much smaller CSV files.

## Questions

- How effectively do states use their federal funding?
- How do school's discipline systems treat students of different races and
sexes?
- How effectively do schools encourage their students to participate in
standardized testing (such as the SAT and ACT)?
- How do schools spend their federal funding?

## Structure

Each tab explores a different aspect of America's school systems, and visualizes
one of the questions listed above.

## Project Creators

- Haruki Takada
- Zak Geilani
- Max Kinsel






